config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :posts, only: %w[show] do
    resources :votes, only: %w[create]
    resources :comments, only: %w[create]
  end
  resources :votes, only: %w[destroy]
  resources :comments do
    resources :reactions, only: %w[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < Interaction
  has_many :reactions, -> { where(type: 'Reaction') }, class_name: 'Interaction', as: :interactable, dependent: :destroy

  validates :content, presence: true
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :user
  belongs_to :interactable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :interactions, as: :interactable, dependent: :destroy
  has_many :comments, -> { where(type: 'Comment') }, class_name: 'Interaction', as: :interactable

  has_many :votes, -> { where(type: 'Vote') }, class_name: 'Interaction', as: :interactable

  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :author, presence: true
  validates :post_type, presence: true
  validates :score, presence: true, numericality: { only_integer: true }

end

app/models/reaction.rb
class Reaction < Interaction
  validates :content, presence: true
  validate :check_type

  private

  def check_type
    if self.interactable.class != Comment
      errors.add(:reaction, 'Reaction can only have a Comment on interactable_type')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :interactions, dependent: :destroy

  validates :username, presence: true
end

app/models/vote.rb
class Vote < Interaction
  validates :user_id, uniqueness: { scope: [:interactable_type, :interactable_id] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :voted, :unvoted, :alert

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.new(comments_params)
    @comment.user = current_user
    @comment.interactable = @post
    @reaction = Reaction.new
    if @comment.save
      respond_to do |format|
        format.turbo_stream do
           render turbo_stream: turbo_stream.append(:comments, partial: "posts/comment",
            target: "comments", locals: { comment: @comment, post: @post, reaction: @reaction })
        end
        format.html { redirect_to post_path(@post) }
      end
    else
      render "posts/show", status: :unprocessable_entity
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @posts = Post.order(:score).last(30).reverse
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @reaction = Reaction.new
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def create
    @comment = Comment.find_by(id: params[:comment_id])
    @reaction = Reaction.new(reactions_params)
    @reaction.interactable = @comment
    @reaction.user = current_user
    @post = Post.find_by(id: @comment.interactable.id)
    if @reaction.save
      redirect_to post_path(@comment.interactable)
    else
      redirect_to post_path(@comment.interactable), status: :unprocessable_entity
    end
  end

  private

  def reactions_params
    params.require(:reaction).permit(:content)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @new_vote = Vote.create(user: current_user, interactable: @post)
    if @new_vote.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [turbo_stream.replace(:flashes, partial: "shared/flashes", target: "flashes", locals: { voted: "Votre vote à bien été ajouté ! 🔥" }),
                                turbo_stream.update("post-#{@post.id}-content", partial: "pages/post_content", locals: { post: @post })]
        end
        format.html { redirect_to root_path, voted: "Votre vote à bien été ajouté ! 🔥" }
      end
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end

  def destroy
    vote = Vote.find_by(id: params[:id])
    if vote.destroy
      redirect_to root_path, unvoted: "Votre vote à bien été retiré 😢"
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNewsCopyCat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <div class="container">
      <%= render "shared/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_post.html.erb
<div class="d-flex text-black" id="post-<% post.id %>">
  <small class="text-secondary me-3"><%= "0" if index < 9 %><%= index + 1 %>.</small>
  <%= render "pages/post_content", post: post %>
</div>
<hr class="m-0">

app/views/pages/_post_content.html.erb
<div class="d-flex" id="post-<%= post.id %>-content">
  <% vote = post.votes.find_by(user: current_user) %>
  <% if vote %>
    <%= link_to vote_path(vote), data: { turbo_method: :delete } do %>
    <i class="fa-solid fa-caret-down mt-2" style="color:rgb(255, 0, 0);"></i>
    <% end %>
  <% else %>
    <%= link_to post_votes_path(post.id), data: { turbo_method: :post } do %>
    <i class="fa-solid fa-caret-up mt-2" style="color: #ff6600;"></i>
    <% end %>
  <% end %>
  <div class="d-flex flex-column ms-2">
    <small>
      <%= link_to post.title, post_path(post), class: "text-decoration-none text-black" %>
      <span class="text-secondary post-url">
        (<%= link_to nil, post.url %>)
      </span>
    </small>
    <small id="post-<%= post.id%>-score" class="text-secondary"><%= post.score + post.votes.count %> points | by <%= post.author %></small>
  </div>
</div>

app/views/pages/home.html.erb
<div class="bg-sable" id="posts" data-controller="sweetalert">
  <% @posts.each_with_index do |post, index| %>
    <div class="d-flex px-4 py-2 flex-column" id="<%= post.id %>">
      <%= render "pages/post", post: post, index: index %>
    </div>
   <% end %>
</div>

app/views/posts/_comment.html.erb
<div class="bg-white d-flex flex-column border border-2 border-warning p-4 text-black post-comment w-50" data-controller="emoji-picker" id="comment-<%= comment.id %>">
  <u><%= comment.created_at.strftime("%e %B %Y at %k:%M") %></u>
  <p class="mb-4 fs-5"><%= comment.content %></p>
  <small class="comment-author">By <%= comment.user.username %></small>
  <%= render "posts/reaction_form", comment: comment, reaction: reaction  %>
  <div class="div-picker">
    <% comment.reactions.each do |reaction| %>
      <%= reaction.content %>
    <% end %>
    <i class="fa-solid fa-face-smile ms-1" data-action="click->emoji-picker#openPicker" style="cursor: pointer;"></i>
    <span class="picker-placeholder"></span>
  </div>
</div>

app/views/posts/_comment_form.html.erb
<div class="w-50">
  <%= simple_form_for [post, comment], data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |f| %>
    <%= f.input :content, as: :text, label: false, input_html: { class: "text-black" }, required: true  %>
    <%= f.submit "Leave a comment", class: "btn btn-warning text-white" %>
  <% end %>
</div>

app/views/posts/_reaction_form.html.erb
<%= simple_form_for [comment, reaction] do |f| %>
  <%= f.input :content, as: :hidden %>
<% end %>

app/views/posts/show.html.erb
<div class="container bg-sable p-4">
  <h1 class="text-black fs-4"><%= @post.title %></h1>
  <p class="text-secondary"><%= link_to nil, @post.url, class: "text-warning fs-6 text-decoration-none" %> | <%= @post.post_type %> | by <%= @post.author %> | <%= @post.score + @post.votes.count %> vote<%= @post.votes.count > 1 ? "s" : "" %> | <%= @post.comments.count %> comment<%= @post.comments.count > 1 ? "s" : "" %> </p>
  <div class="gap-3 d-flex flex-column mb-4" id="comments">
    <% if @post.comments.count.zero? %>
      <p class="text-secondary">No comment for this post.</p>
    <% end %>
    <% @post.comments.each do |comment| %>
      <%= render "posts/comment", comment: comment, reaction: @reaction %>
    <% end %>
  </div>
  <%= render "posts/comment_form", comment: @comment, post: @post %>
</div>

app/views/shared/_flashes.html.erb
<div id="flashes">
  <% if alert %>
    <hr data-controller="sweetalert" data-sweetalert-flashes-value="alert:<%= alert %>" hidden/>
  <% elsif notice %>
    <hr data-controller="sweetalert" data-sweetalert-flashes-value="notice:<%= notice %>" hidden/>
  <% elsif voted %>
    <hr data-controller="sweetalert" data-sweetalert-flashes-value="voted:<%= voted %>" hidden/>
  <% elsif unvoted %>
    <hr data-controller="sweetalert" data-sweetalert-flashes-value="unvoted:<%= unvoted %>" hidden/>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-warning mt-2 p-1">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <div class="bg-warning border border-3 border-white logo text-center">
          <span class="text-white">Y</span>
        </div>
      <% end %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <h1 class="text-black fs-4 fw-bold m-0">HackerNews</h1>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>